language: php
os: linux

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

jobs:
  include:
    - php: 7.2.0
      env: dependencies=lowest
  allow_failures:
      - php: nightly

before_script:
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-stable; else composer update --ignore-platform-reqs; fi;

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - vendor/bin/php-coveralls -v
